// Generated by CoffeeScript 1.6.3
(function() {
  var Animal;

  window.x = 3 + 3;

  window.func = function(string) {
    return console.log(string);
  };

  func("Hello");

  Animal = (function() {
    function Animal(name, age, gender, species) {
      this.name = name;
      this.age = age;
      this.gender = gender;
      this.species = species;
      this.toys = [];
    }

    Animal.prototype.toString = function() {
      return "" + this.name + " is a " + this.age + " year old " + this.gender + " " + this.species + " that loves " + (this.toys.join(', '));
    };

    return Animal;

  })();

  window.larry = new Animal("Larry", 7, "Male", "Bird");

}).call(this);
